### ISSUE TITLE
What happened to the AppImage?

### ISSUE THREAD

**Issue by probonopd** [Mokkapps/scrum-daily-standup-picker#5]
What happened to the AppImage in the recent releases?

**Comment by Mokkapps** [comment]
As far as I can tell you my application does not work as AppImage because I do not use asar and therefore I cannot write files outside the application.

But I can build you an AppImage version if you want to test it?

**Comment by probonopd** [comment]
Sure, once there is an AppImage I'll be happy to test it.

**Comment by Mokkapps** [comment]
Here you go: https://github.com/Mokkapps/scrum-daily-standup-picker/releases/download/v1.2.0/scrum-daily-standup-picker-1.2.0-x86_64.AppImage
